# BootCamp 2019 - Week 1

## PyIntro - Numpy Intro

Author: Martina Fraschini

In [1]:
# import packages
import numpy as np

### Problem 1

In [6]:
# define matrices
A = np.array([[3, -1, 4],[1, 5, -9]])
B = np.array([[2, 6, -5, 3],[5, -8, 9, 7],[9, -3, -2, -3]])

# compute multiplication
multiplication = np.dot(A, B)
print("A * B =")
print(multiplication)

A * B =
[[ 37  14 -32 -10]
 [-54  -7  58  65]]


### Problem 2

In [9]:
# define matrix
A = np.array([[3, 1, 4],[1, 5, 9],[-5, 3, 1]])

# compute square and cube of matrix
A2 = np.dot(A, A)
A3 = np.dot(A2, A)

result = - A3 + 9*A2 - 15*A
print(result)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Problem 3

In [29]:
# define matrices
A = np.ones((7,7))
A = np.triu(A)

B = np.full_like(A,-6)
B = np.tril(B)
B += 5

# compute product
AB = np.dot(A, B)
prod = np.dot(AB, A)

# change data type
prod = prod.astype(np.int64)

print(prod)

[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


### Problem 4

In [32]:
# define function
def arrayfun(x):
    y = np.copy(x)
    mask = y < 0
    y[mask] = 0
    return y

# demo for function
a = np.array([1, 4, -7, 9, 3, -5])
b = arrayfun(a)
print(b)

[1 4 0 9 3 0]


### Problem 5

In [58]:
# define matrices
A = np.arange(6).reshape((3,2)).T

B = np.full((3,3), 3)
B = np.tril(B)

C = np.diag(np.full(3,-2))

# block matrix
block1 = np.vstack((np.zeros((3,3)), A, B))
block2 = np.vstack((A.T, np.zeros((5,2))))
block3 = np.vstack((np.eye(3), np.zeros((2,3)), C))

block = np.hstack((block1, block2, block3))

print(block.astype(np.int64))

[[ 0  0  0  0  1  1  0  0]
 [ 0  0  0  2  3  0  1  0]
 [ 0  0  0  4  5  0  0  1]
 [ 0  2  4  0  0  0  0  0]
 [ 1  3  5  0  0  0  0  0]
 [ 3  0  0  0  0 -2  0  0]
 [ 3  3  0  0  0  0 -2  0]
 [ 3  3  3  0  0  0  0 -2]]


### Problem 6

In [64]:
# define funciton
def row_stochastic(M):
    rowsum = M.sum(axis=1).reshape((-1,1))
    return M / rowsum

# demo for function
A = np.array([[1, 1, 1],[3, 0, 0],[1, 1, 2]])
print(row_stochastic(A))

[[0.33333333 0.33333333 0.33333333]
 [1.         0.         0.        ]
 [0.25       0.25       0.5       ]]


### Problem 7

In [80]:
# load array
grid = np.load("grid.npy")

right = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
down = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
diag_r = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
diag_l = np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1,1:-2] * grid[3:,:-3])

winner = np.max((right, down, diag_r, diag_l))
print(winner)

70600674
